# Generated by Django 4.2.1 on 2023-06-13 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fstr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerevalAdded',
            new_name='Pereval',
        ),
    ]
